on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ACCESS_TOKEN}}@github.com/AKramarenko/main.git"
          source_branch: "main"
          destination_repo: "https://${{ACCESS_TOKEN}}@github.com/AKramarenko/mirror1.git"
          destination_branch: "main"